---
title: "string practice"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am – HVAC system down, facilities management alerted",
                       "8:24am – Elevator North out of service",
                       "12:41am – Fire alarm, UCSB fire responded and cleared",
                       "9:58pm – Campus point emergency siren, UCPD responded")
)
```

-   Replace the \"Engr\" with \"Engineering\" in the `building` column

```{r}
alarm_report %>% 
  mutate(building = str_replace_all(building, pattern = "Engineering", replacement = "Engr"))
```

-   

-   Separate the `building` column into two separate columns, `building` and `wing`, separated at the dash

    ```{r}

    ```

-   Only keep observations with the word \"responded\" in the `alarm_message` column

    ```{r}
    alarm_report %>% 
      filter(str_detect(alarm_message, pattern = "responded"))
    ```

-   Separate the message *time* from the rest of the message by separating at `--`

    ```{r}

    ```

-   Convert the date column to a Date class using `lubridate`

    ```{r}
    alarm_report %>% 
      mutate(date = lubridate::ymd(date))
    ```
